export const CONFIG = {
  MIN_PLAYERS: 3,
  MAX_PLAYERS: 12,
  MAX_NAME_LENGTH: 20,
  MAX_QUESTION_LENGTH: 140,
  MAX_ANSWER_LENGTH: 140,
  MAX_CHAT_LENGTH: 200,
  NOTE_MIN: 1,
  NOTE_MAX: 10,
  RECONNECT_GRACE: 30,
  ROOM_CODE_LENGTH: 4,
  REACTIONS: ['😂', '😮', '👏', '❤️', '😢', '🔥'],
};
